# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://railway_digital_twin_db:5432/railway_dt
spring.datasource.username=postgres
spring.datasource.password=110319

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================
server.port=8080
server.servlet.context-path=/api

# ===============================
# CORS
# ===============================
cors.allowed.origins=http://localhost:5173,http://localhost:3000

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.com.railway.digitaltwin=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO

# ===============================
# MQTT
# ===============================
mqtt.broker.url=tcp://railway_digital_twin_mosquitto:1883
mqtt.client.id=railway-backend
mqtt.topic=railway/sensors/#

# ===============================
# NB-IoT (future use)
# ===============================
nbiot.gateway.enabled=true
nbiot.gateway.endpoint=/api/nbiot/sensors
nbiot.gateway.protocol=HTTP